version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next-ninja
    ports:
      - '3000:3000'
    volumes:
      - '/app/node_modules'
      - './:/app'
