// Global Styles
import './_assets/styles/global.scss'

// Next
import type { Metadata } from 'next'

// Fonts
import { Poppins } from 'next/font/google'

// Components
import { Navbar } from './_components'

const poppins = Poppins({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				{/* Navbar */}
				<Navbar />
				{/* End Navbar */}

				{children}
			</body>
		</html>
	)
}
